let project = new Project('TrilateralKha_fxgTest');
project.addAssets('Assets/**');
project.addShaders('Shaders/**');
project.addSources('src');
project.addLibrary('trilateral');
project.addLibrary('trilateralXtra');
project.addLibrary('hxPolyK');
project.windowOptions.width = 800;
project.windowOptions.height = 600;
resolve( project );